# Site settings
title: Beagleworx Studio
blogtitle: Beagleworx Labs Tech Blog
email: beagleworxlabs@icloud.com
bio:                'Beagleworx Labs by Rolly Ceballos'
locale:             en_US
description: "Beagleworx Labs Web Page"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blogs.beagleworx.com" # the base hostname & protocol for your site

twitter_username:
github_username: rceba04


# Comments
disqus_shortname:   beagleworx-labs

# Social
analytics-id:       UA-114720210-1
twitter:            "default"
facebook:           beagleworxlabs
instagram:          beagleworxlabs
github:             rceba04

# personal
location:           Bacolod City, PH
phone:              111-222-3333
email:              beagleworxlabs@icloud.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /blog_images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
